add_newline = false
format = """$character"""
right_format = """$directory"""
continuation_prompt = '▶▶ '

[character]
# success_symbol = '[󰱯  >>](bold green)'
success_symbol = '[~ λ](bold green)'
# error_symbol = '[󰱯  >>](bold red)'
error_symbol = '[~ λ](bold red)'
vimcmd_symbol = '[ >>](bold blue)'
vimcmd_visual_symbol = '[ >>](bold magenta)'

[directory]
style = "bold cyan"

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true
