#+title: DOOM EMACS LITERATE CONFIG
#+author: s.takoor
#+auto_tangle: t
#+startup: showeverything
#+filetags: :doom:emacs:config:org:

#+begin_quote
A configuration without change is meaningless. By enduring thy tweaks and overcoming thy challenges, thou shalt obtain a powerful, unmatched setup.
#+end_quote

* TL;DR
This is my literate *DOOM EMACS* configuration, written in [[https://orgmode.org/][org]] format. The configuration contains the code blocks for the three main files: ~init.el~, ~config.el~, and ~packages.el~, required to configure ~Doom Emacs~, which is written in ~Emacs Lisp~. The function ~org-babel-tangle~ or the ~org-auto-tangle~ package can be used to extract the source code blocks from this file into their own source-specific files.

** TABLE OF CONTENTS :toc:quote:
#+BEGIN_QUOTE
- [[#tldr][TL;DR]]
- [[#emacs-installation][EMACS INSTALLATION]]
  - [[#prerequisites][PREREQUISITES]]
  - [[#dependencies][DEPENDENCIES]]
  - [[#emacs][EMACS]]
  - [[#doom-emacs][DOOM EMACS]]
  - [[#pro-tip][PRO TIP]]
- [[#configel][CONFIG.EL]]
  - [[#about][ABOUT]]
  - [[#beacon-mode][BEACON MODE]]
  - [[#centaur-tabs][CENTAUR-TABS]]
  - [[#ellama][ELLAMA]]
  - [[#fonts][FONTS]]
  - [[#frame-opacity][FRAME OPACITY]]
  - [[#imenu-list][IMENU-LIST]]
  - [[#jinx][JINX]]
  - [[#line-numbers][LINE NUMBERS]]
  - [[#line-spacing][LINE SPACING]]
  - [[#minimal-ui][MINIMAL UI]]
  - [[#modeline][MODELINE]]
  - [[#spacious-padding][SPACIOUS PADDING]]
  - [[#modus-theme][MODUS THEME]]
  - [[#org-auto-tangle][ORG-AUTO-TANGLE]]
  - [[#org-alert][ORG-ALERT]]
  - [[#org-babel-configuration][ORG-BABEL CONFIGURATION]]
  - [[#org-mode-configuration][ORG-MODE CONFIGURATION]]
  - [[#org-modern][ORG-MODERN]]
  - [[#org-latex][ORG-LATEX]]
  - [[#pdf-tools][PDF-TOOLS]]
  - [[#rainbow-mode][RAINBOW MODE]]
  - [[#rss][RSS]]
- [[#initel][INIT.EL]]
- [[#packagesel][PACKAGES.EL]]
#+END_QUOTE

* EMACS INSTALLATION
There exists various options for installing ~Emacs~ on ~macOS~. Ensure a package manager is installed to facilitate this process. The following assumes the package manager is ~Homebrew~.

** PREREQUISITES
Before installing ~Doom Emacs~, ensure the following packages are installed:
- Git
- Emacs
- ripgrep
- GNU Find
- fd (optional)

** DEPENDENCIES
#+begin_src sh
# required dedenpdencies
brew install git ripgrep
# optional dependencies
brew install coreutils fd findutils
# install clang
xcode-select --install
#+end_src

** EMACS
There are three formulas that are considered as the best options for ~Doom~. I prefer using ~emacs-plus~ as it offers a wide range of extra functionality over the regular Emacs package.
- ~emacs-mac~ formula offers good integration with ~macOS~, native emojis and better childframe support.
- ~emacs~ formula is another option but does ~not~ provide a ~Emacs.app~.
- ~emacs-plus~ formula from [[https://github.com/d12frosted/homebrew-emacs-plus][d12frosted]].
#+begin_src sh
brew tap d12frosted/emacs-plus
# install emacs+ with some additional options
brew install emacs-plus --with-native-comp --with-modern-doom3-icon
cp -r /opt/homebrew/opt/emacs-plus/Emacs.app /Applications/
#+end_src

** DOOM EMACS
After installing ~Emacs~ and ~Doom~'s dependencies, ~Doom Emacs~ can be installed:
#+begin_src sh
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src

** PRO TIP
I make use of the following keybindings to spun up ~emacsclient~ via the [[https://github.com/koekeishiya/skhd][skhd]] package: a simple hotkey daemon for ~macOS~.
#+begin_src sh
shift + cmd - e : emacsclient -c -n -a ''
#+end_src

* CONFIG.EL
** ABOUT
Some general info
#+begin_src emacs-lisp :tangle "config.el"
(setq user-full-name "s.t"
      user-mail-address "shashiduth.takoor@gmail.com")
#+end_src

** BEACON MODE
#+begin_src emacs-lisp :tangle "config.el"
(beacon-mode t)
#+end_src

** CENTAUR-TABS
#+begin_src emacs-lisp :tangle "config.el"
(setq centaur-tabs-default-font "JetBrainsMono NF" ;;Iosevka NF
      centaur-tabs-set-bar 'right
      centaur-tabs-set-icons t
      centaur-tabs-gray-out-icons 'buffer
      centaur-tabs-height 24
      centaur-tabs-set-modified-marker t
      centaur-tabs-style "bar"
      centaur-tabs-close-button "â¨‚"
      centaur-tabs-modified-marker "â¨€")
#+end_src

** ELLAMA
The ~Emacs Large LAnguage Model Assistant (ELLAMA)~ module is used for interacting with large language models from Emacs.
#+begin_src emacs-lisp :tangle "config.el"
;; (require 'ellama)
;; (add-hook 'ellama-mode-hook (lambda () (setopt ellama-language "English")))
;; (require 'llm-ollama)
;; (setq ellama-provider (make-llm-ollama :chat-model "gemma:2b" :embedding-model "gemma:2b"))
#+end_src

** FONTS
A ~nerd font~ with support for glyphs (icons).
#+begin_src emacs-lisp :tangle "config.el"
(setq doom-font (font-spec :family "JetBrainsMono NF" :size 12 :weight 'light)
      doom-big-font (font-spec :family "JetBrainsMono NF" :size 12 :weight 'light)
      doom-serif-font (font-spec :family "JetBrainsMono NF" :size 12 :weight 'light)
      doom-symbol-font (font-spec :family "JetBrainsMono NF" :size 12 :weight 'light)
      doom-variable-pitch-font (font-spec :family "JetBrainsMono NF" :size 12 :weight 'light))
#+end_src

** FRAME OPACITY
#+begin_src emacs-lisp :tangle "config.el"
(set-frame-parameter (selected-frame) 'alpha '(70 . 90))
(add-to-list 'default-frame-alist '(alpha . (70 . 90)))
#+end_src

** IMENU-LIST
#+begin_src emacs-lisp :tangle "config.el"
(setq imenu-list-auto-resize t
      imenu-list-focus-after-activation t)
#+end_src

** JINX
~jinx~ is a fast just-in-time spell-checker for Emacs.
#+begin_src emacs-lisp :tangle "config.el"
(require 'jinx)

;; Enable Jinx globally
(add-hook 'emacs-startup-hook #'global-jinx-mode)
#+end_src

** LINE NUMBERS
#+begin_src emacs-lisp :tangle "config.el"
(setq display-line-numbers-type 'relative)
#+end_src

** LINE SPACING
#+begin_src emacs-lisp :tangle "config.el"
(setq-default line-spacing 0)
#+end_src

** MINIMAL UI
#+begin_src emacs-lisp :tangle "config.el"
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(show-paren-mode 1)
(add-to-list 'default-frame-alist '(undecorated-round . t))
#+end_src

** MODELINE
#+begin_src emacs-lisp :tangle "config.el"
(require 'doom-modeline)

(setq doom-modeline-enable-word-count t
      doom-modeline-battery t
      doom-modeline-icon t
      doom-modeline-time t
      doom-modeline-time-icon t
      doom-modeline-lsp t)
#+end_src

** SPACIOUS PADDING
#+begin_src emacs-lisp :tangle "config.el"
;; (require 'spacious-padding)


(setq spacious-padding-widths
      '( :internal-border-width 15
         :header-line-width 4
         :mode-line-width 6
         :tab-width 4
         :right-divider-width 1
         :scroll-bar-width 8
         :left-fringe-width 20
         :right-fringe-width 20))

(setq spacious-padding-subtle-mode-line
      `( :mode-line-active 'default
         :mode-line-inactive vertical-border))

;; Enable spacious-padding mode
(spacious-padding-mode 1)
#+end_src

** MODUS THEME
#+begin_src emacs-lisp :tangle "config.el"
(require 'modus-themes)

(custom-set-variables
 '(modus-themes-variable-pitch-ui t)
 '(modus-themes-bold-constructs t)
 '(modus-themes-italic-constructs t)
 '(modus-themes-mixed-fonts t)
 '(modus-themes-prompts '(italic bold))
 '(modus-themes-completions '((matches . (extrabold underline))
                              (selection . (semibold italic text-also underline))))
 '(modus-themes-org-blocks 'gray-background)
 '(modus-themes-headings
   '((1 . (variable-pitch 1.5))
     (2 . (1.3))
     (agenda-date . (1.3))
     (agenda-structure . (variable-pitch light 2.2))
     (t . (1.15))))) ;; Default size for other headings
(load-theme 'modus-vivendi-tritanopia t)
#+end_src

** ORG-AUTO-TANGLE
The ~org-auto-tangle~ package automatically tangle org files on save. This is achieved by adding the option ~#+auto_tangle: t~. If instead you would like to manually tangle the org file on save, the following emacs keybindings can be used ~C-c C-v C-t~

The tangling process happens asynchronously, therefore it will not block the current emacs session.
#+begin_src emacs-lisp :tangle "config.el"
(require 'org-auto-tangle)
(add-hook 'org-mode-hook #'org-auto-tangle-mode)
(setq org-auto-tangle-default t)
#+end_src

** ORG-ALERT
#+begin_src emacs-lisp :tangle "config.el"
(require 'org-alert)
(setq org-alert-interval 1200
      org-alert-notify-cutoff 10
      org-alert-notify-after-event-cutoff 10
      org-alert-notification-title "Org Alert Reminder!")

(require 'alert)
(setq alert-default-style 'osx-notifier)
#+end_src

** ORG-BABEL CONFIGURATION
#+begin_src emacs-lisp :tangle "config.el"
;; Set the default Python interpreter to Python3
(setq org-babel-python-command "python3")

;; Set ditaa path
(setq org-ditaa-jar-path "/opt/homebrew/Cellar/ditaa/0.11.0_1/libexec/ditaa-0.11.0-standalone.jar")
#+end_src

** ORG-MODE CONFIGURATION
#+begin_src emacs-lisp :tangle "config.el"
(setq org-directory "~/Documents/orgfiles/"
      org-auto-align-tags nil
      org-tags-column 0
      org-fold-catch-invisible-edits 'show-and-error
      org-special-ctrl-a/e t
      org-insert-heading-respect-content t
      org-export-headline-levels 5
      org-log-done 'time
      org-log-into-drawer t
      org-edit-src-content-indentation 0

      ;; Org styling, hide markup, etc.
      org-hide-emphasis-markers t
      org-pretty-entities t
      org-ellipsis " â–¼"
      org-hide-leading-stars t
      org-src-preserve-indentation nil
      org-src-tab-acts-natively t
      org-startup-indented nil

      ;; Agenda styling
      org-agenda-window-setup 'current-window
      org-agenda-files '("~/Documents/orgfiles/agenda.org")
      org-agenda-tags-column 0
      org-agenda-block-separator ?â”€
      org-agenda-time-grid
      '((daily today require-timed)
        (800 1000 1200 1400 1600 1800 2000)
        " â”„â”„â”„â”„â”„ " "â”„â”„â”„â”„â”„â”„â”„â”„â”„â”„â”„â”„â”„â”„â”„")
      org-agenda-current-time-string
      "â­  now â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€")
#+end_src

** ORG-MODERN
The ~org modern~ package implements a modern style for Org buffers using font locking and text properties. The package styles headlines, keywords, tables and source blocks. 
#+begin_src emacs-lisp :tangle "config.el"
(require 'org-modern)

;; Customize org-modern settings
(setq org-modern-star '("â—‰" "â—‹" "âœ¸" "âœ¿" "âœ¤" "âœœ" "â—†" "â–¶")
      org-modern-table-vertical 1
      org-modern-table-horizontal 0.2
      org-modern-horizontal-rule t)

;; Enable global-org-modern-mode
(global-org-modern-mode)
#+end_src

** ORG-LATEX
#+begin_src emacs-lisp :tangle "config.el"
(require 'ox-latex)

;; Set LaTeX compiler to XeLaTeX
(add-hook! 'latex-mode-hook
  (setq TeX-engine 'xelatex) 99)

;;(setq org-latex-pdf-process (list "latexmk -pdflatex='xelatex -shell-escape -interaction nonstopmode' -pdf -output-directory=%o %f"))

(with-eval-after-load 'ox-latex
  (add-to-list 'org-latex-classes
               '("article"
                 "\\documentclass[letterpaper]{article}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")
                 )))

(require 'engrave-faces-latex)
(setq org-latex-src-block-backend'engraved)
#+end_src

** PDF-TOOLS
#+begin_src emacs-lisp :tangle "config.el"
(require 'pdf-tools)

(add-hook 'doc-view-mode-hook 'pdf-tools-install)

(setq-default pdf-view-use-scaling t
              pdf-view-use-imagemagick nil)
#+end_src

** RAINBOW MODE
#+begin_src emacs-lisp :tangle "config.el"
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
#+end_src

** RSS
The ~elfeed~ module is an RSS reader for ~Emacs~. The ~+org~ module flag in my ~init.el~ allows the use of ~org-mode~ to manage RSS feeds. I've added an example of my ~elfeed.org~ file which can be found [[https://github.com/s-takoor/emacs-org-docs/tree/main/rss][here]]. This file is located in my ~{org-directory}/elfeed.org~.
#+begin_src emacs-lisp :tangle "config.el"
(require 'elfeed-goodies)

;; News filtering
(after! elfeed
  (setq elfeed-search-filter "@2-weeks-ago"))

;; Automatically updating feed when opening elfeed
(add-hook! 'elfeed-search-mode-hook #'elfeed-update)

(global-set-key (kbd "C-x w") 'elfeed)
#+end_src

* INIT.EL
The ~init.el~ file controls what ~Doom~ modules are enabled and what order they load in. Remember to run ~doom sync~ after modifying it!

#+begin_quote
ó°ƒ Press ~SPC h d h~ (or ~C-h d h~ for non-vim users) to access Doom's documentation. There you'll find a link to Doom's Module Index where all of our modules are listed, including what flags they support.

Move your cursor over a module's name (or its flags) and press ~K~ (or ~C-c c k~ for non-vim users) to view its documentation. This works on flags as well (those symbols that start with a plus).

Alternatively, press ~gd~ (or ~C-c c d~) on a module to browse its directory (for easy access to its source code).
#+end_quote

#+begin_src emacs-lisp :tangle "init.el"
(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       ;;company           ; the ultimate code completion backend
       (corfu +orderless +dabbrev)               ; complete with cap(f), cape and a flying feather!
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       (vertico +childframe +icons)           ; the search engine of the future

       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       (emoji +unicode)  ; ðŸ™‚
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       (ligatures +extra)         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       tabs              ; a tab bar for Emacs
       treemacs          ; a project drawer, like neotree but cooler
       unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +lsp +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       word-wrap         ; soft wrapping with language-aware indent

       :emacs
       (dired +icons)             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       (ibuffer +icons)         ; interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs

       :checkers
       (syntax +childframe +flymake +icons)              ; tasing you for every semicolon you forget
       (spell +enchant) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;; ansible               ; a crucible for infrastructure as code
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;collab            ; buffers with friends
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv              ; be direct about your environment
       ;;docker              ; port everything to containers
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       (lookup +dictionary +docsets +offline)              ; navigate your code and its documentation
       (lsp +eglot)               ; M-x vscode
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;; rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       tree-sitter       ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       tty               ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       ;;(cc +lsp)         ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       (json +lsp +tree-sitter)              ; At least it ain't XML
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       ;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       (latex +latexmk +lsp +fold)             ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       (lua +lsp +tree-sitter)               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       (nix +lsp +tree-sitter)               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org +hugo +present)              ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       ;; (python +tree-sitter)            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp +tree-sitter)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       (sh +fish +lsp +tree-sitter)               ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubes
       (yaml +lsp + tree-sitter)              ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;; emms
       everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       (rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       ;; literate
       (default +bindings +smartparens))
#+end_src

* PACKAGES.EL
The ~package.el~ file lists all packages to be installed with ~Doom Emacs~. Each line specifies the name of a package and any additional configuration options. After declaring the package name in the ~packages.el~ file, you will have to run ~doom sync~ on the command line or ~SPC h r r~, then restart ~Emacs~ for the changes to take effect -- or use ~M-x doom/reload~.

To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
(package! some-package)

To install a package directly from a remote git repo, you must specify a `:recipe'. You'll find [[https://github.com/radian-software/straight.el#the-recipe-format][documentation]] on what `:recipe' accepts here:
(package! another-package
  :recipe (:host github :repo "username/repo"))

If the package you are trying to install does not contain a PACKAGENAME.el file, or is located in a subdirectory of the repo, you'll need to specify
`:files' in the `:recipe':
(package! this-package
  :recipe (:host github :repo "username/repo"
           :files ("some-file.el" "src/lisp/*.el")))

If you'd like to disable a package included with Doom, you can do so here with the `:disable' property:
(package! builtin-package :disable t)

You can override the recipe of a built in package without having to specify all the properties for `:recipe'. These will inherit the rest of its recipe from Doom or MELPA/ELPA/Emacsmirror:
(package! builtin-package :recipe (:nonrecursive t))
(package! builtin-package-2 :recipe (:repo "myfork/package"))

Specify a `:branch' to install a package from a particular branch or tag. This is required for some packages whose default branch isn't 'master'
(package! builtin-package :recipe (:branch "develop"))

Use `:pin' to specify a particular commit to install.
(package! builtin-package :pin "1a2b3c4d5e")

Doom's packages are pinned to a specific commit and updated from release to release. The `unpin!' macro allows you to unpin single packages...
(unpin! pinned-package)
...or multiple packages
(unpin! pinned-package another-pinned-package)
...Or *all* packages (NOT RECOMMENDED; will likely break things)
(unpin! t)

#+begin_src emacs-lisp :tangle "packages.el"
(package! beacon)
(package! elfeed-goodies)
;; (package! ellama)
(package! engrave-faces)
(package! fish-mode)
(package! imenu-list)
(package! jinx)
(package! modus-themes)
(package! org-alert)
(package! org-auto-tangle)
(package! org-modern)
(package! ns-auto-titlebar)
(package! osx-dictionary)
(package! osx-trash)
(package! spacious-padding)
#+end_src
