# -- aliases -- #
alias sync='doom sync && doom doctor'
alias purge='brew cleanup --prune=all'
alias list='brew list'
alias switch='brew update && brew upgrade'
alias cat='bat --color=always'
alias df='df -h'
alias ls='eza -al --icons --color=always --group-directories-first'
alias la='eza -a --icons --color-always --group-directories-first'
alias ll='eza -l --icons --color=always'
alias lt='eza -aT --color=always'
alias vi='nvim'
alias vim='nvim'
alias cp='xcp'
alias cd='z'
