import:
  - ~/.config/alacritty/colors.yml
  - ~/.config/alacritty/fonts.yml

env:
  TERM: xterm-256color

shell:
  program: /opt/homebrew/bin/tmux
  args:
    - new-session
    - -D
    - -A
    - -s
    - main

window:
  opacity: 0.7
  dimensions:
    columns: 200
    lines: 50

  padding:
    x: 40
    y: 40


  decorations: buttonless
  startup_mode: windowed
  dynamic_title: false

  scrolling:
    history: 100000
    multiplier: 3

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    vi_mode_style:
    unfocused_hollow: false

# TMUX SHORTCUTS      
key_bindings:
  # NEW TAB
  - { key: T, mods: Command, chars: "\x02\x63" }
  # RENAME PANE
  - { key: Comma, mods: Command, chars: "\x02\x2c" }
  # WINDOW VIEWER
  - { key: W, mods: Command, chars: "\x02\x77" }
  # SPLIT RIGHT
  - { key: L, mods: Command, chars: "\x02\x25" }
  # SPLIT DOWN
  - { key: J, mods: Command, chars: "\x02\x22" }
  # SWITCH TO PANE 1 - 9
  - { key: Key1, mods: Command, chars: "\x02\x31" }  
  - { key: Key2, mods: Command, chars: "\x02\x32" }  
  - { key: Key3, mods: Command, chars: "\x02\x33" }  
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }  
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }  
  - { key: Key8, mods: Command, chars: "\x02\x38" }  
  - { key: Key9, mods: Command, chars: "\x02\x39" }  

live_reload_config: true
