import:
  - ~/.config/alacritty/fonts.yml
  - ~/.config/alacritty/colors.yml

env:
  TERM: xterm-256color

window:
  opacity: 0.9
  dimensions:
    columns: 200
    lines: 50

  padding:
    x: 40
    y: 40

  decorations: buttonless
  startup_mode: Windowed
  dynamic_title: false

  scrolling:
    history: 10000
    multiplier: 3

cursor:
  style:
    shape: Block
    blinking: On

  unfocused_hollow: false

key bindings:
  - { key: Key3,     mods: Alt,     chars: "\x23" }

live_config_reload: true

