font:
  normal:
    family: "Iosevka Nerd Font"
    style: Regular
  bold:
    family: "Iosevka Nerd Font"
    style: Bold
  italic:
    family: "Iosevka Nerd Font"
    style: Italic
  bold_italic:
    family: "Iosevka Nerd Font"
    style: Bold Italic
  size: 10
